//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlorOvijatriEntities : DbContext
    {
        public AlorOvijatriEntities()
            : base("name=AlorOvijatriEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Deposit> tbl_Deposit { get; set; }
        public virtual DbSet<tbl_Spending> tbl_Spending { get; set; }
        public virtual DbSet<tbl_UserInfo> tbl_UserInfo { get; set; }
        public virtual DbSet<tbl_UserType> tbl_UserType { get; set; }
    }
}
