//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Spending
    {
        public string SpendingID { get; set; }
        public int Amount { get; set; }
        public string PurposeOfSpending { get; set; }
        public System.DateTime SpendingDate { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string Comment { get; set; }
    }
}
