//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1.Models
{
    using System;

    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;
    
    
    public partial class tbl_UserInfo
    {
        public tbl_UserInfo()
        {
            this.tbl_Deposit = new HashSet<tbl_Deposit>();
        }

        [Remote("IsUserIDExist", "Validation", HttpMethod = "POST", ErrorMessage = "User ID already exists. Please enter a different one.")]
        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "User ID")]
        public string UserID { get; set; }

        [Required]
        [Display(Name = "User Type")]
        public int UserTypeID { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Father's Name")]
        public string FatherName { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Mother's Name")]
        public string MotherName { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Date of Birth")]
        public System.DateTime DOB { get; set; }

        [Required]
        [DataType(DataType.MultilineText)]
        [Display(Name = "Present Address")]
        public string PresentAddress { get; set; }

        [Required]
        [DataType(DataType.MultilineText)]
        [Display(Name = "Permanent Address")]
        public string PermanentAddress { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Occupation")]
        public string Occupation { get; set; }

        [Required]
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Mobile No.")]
        public string Mobile { get; set; }

        [DataType(DataType.Text)]
        [Display(Name = "National ID card No.")]
        public string NID { get; set; }

        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email")]
        public string Email { get; set; }
        public bool IsActive { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        [StringLength(12, MinimumLength = 8)]
        public string Password { get; set; }

        [NotMapped]
        [DataType(DataType.Password)]
        [Display(Name = "Confirm Password")]
        [System.ComponentModel.DataAnnotations.Compare("Password")]
        public string ConfirmPassword { get; set; }
    
        public virtual ICollection<tbl_Deposit> tbl_Deposit { get; set; }
        public virtual tbl_UserType tbl_UserType { get; set; }
    }
}
